#QuickCraft
#By: DroidVengeance
#Version: 1.2
 
#Main Options
menuName:
    "&1Crafting Recipes"
      
itemsMissing:
    "&cYou don't have the required items to craft that!"
     
sneakRightClick:
    true
#Config ends
